services:
  app:
    image: jqknono/weread-challenge:latest
    pull_policy: always
    environment:
      - WEREAD_REMOTE_BROWSER=http://selenium:4444
      # 建立接收插槽
      - WEREAD_COOKIE=${WEREAD_COOKIE}
      - WEREAD_SELECTION=${WEREAD_SELECTION}
      - WEREAD_DURATION=${WEREAD_DURATION}
    volumes:
      - ./data:/app/data
    depends_on:
      selenium:
        condition: service_healthy
    dns:
      - 223.5.5.5
  selenium:
    image: selenium/standalone-chromium:latest
    pull_policy: if_not_present
    shm_size: 2gb
    environment:
      - SE_ENABLE_TRACING=false
      - SE_BIND_HOST=false
    dns:
      - 223.5.5.5
    healthcheck:
      test: ["CMD", "curl", "-f", "http://selenium:4444/status"]
      interval: 5s
      timeout: 60s
      retries: 10
