name: 微信读书自动打卡阅读

on:
  workflow_dispatch: # 支持你在 GitHub 页面手动点击运行
  schedule:
    - cron: '30 0 * * *' # 每天北京时间 08:30 自动运行

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 安装 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: 安装依赖
        run: npm install

      - name: 执行打卡脚本
        env:
          WEREAD_COOKIE: ${{ secrets.WEREAD_COOKIE }}
          WEREAD_SELECTION: -1
        run: node src/weread-challenge.js
